config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'
  resources :public_recipes, controller: 'public_recipes'
  resources :recipe_foods

  resources :foods
  resources :recipes do
      resources :recipe_foods do
        put 'increment_quantity', on: :member
        put 'decrement_quantity', on: :member
      end
      member do
    put :make_private
  end
  end
  resources :users
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes.order(created_at: :desc)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = if @recipe.user_id == current_user.id # check if there is a logged in user
                      RecipeFood.includes(:recipe).where(recipe_id: @recipe.id)
                    else
                      RecipeFood.includes(:recipe, :food).where(recipe_id: @recipe.id)
                    end
    @foods = Food.all
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  def make_private
    @recipe = Recipe.find(params[:id])
    @recipe.update_attribute(:public, !@recipe.public)
    redirect_to recipe_path(@recipe)
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
<div>
  <h2 class="d-flex justify-content-around">
    <%= recipe.name %>
  </h2>

  <% if current_user && recipe.user == current_user %>
  <% if recipe.public %>
    <%= button_to "Public", make_private_recipe_path(recipe), method: :put, class: "btn btn-success", type: "button" %>
  <% else %>
    <%= button_to "Private", make_private_recipe_path(recipe), method: :put, class: "btn btn-danger", type: "button" %>
  <% end %>
<% end %>
</div>
  <p>
    <strong>Preparation time:</strong>
    <%= "#{recipe.preparation_time} Hrs" %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= "#{recipe.cooking_time} Hrs" %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>By:</strong>
    <%= recipe.user.name %>
  </p>

</div>

app/views/recipes/_recipe_prev.html.erb
<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title"><%= recipe.name %></h5>
  </div>
  <div class="card-body">
    <p class="card-text"><%= recipe.description %></p>
    <p><strong>By: <%= recipe.user.name %></strong></p>
    <% if can? :destroy, recipe %>
    <%= button_to "REMOVE", recipe_path(recipe), method: :delete, class: "btn btn-danger", type: "button" %>
    <% end %>
  </div>
<%= link_to "Show this recipe", recipe, class: "btn btn-primary" %>
</div>

app/views/recipes/index.html.erb
<div class="d-flex justify-content-between">
<h1>Recipes</h1>
<%= link_to "New recipe", new_recipe_path, class:"btn btn-warning my-2" %>
</div>

<div id="recipes">
  <% @recipes.each do |recipe| %>
  <% if can? :read, recipe %>
    <%= render 'recipe_prev', recipe: recipe %>
    <%end%>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<%= render @recipe %>
<div>
  <%= link_to "Back to recipes", recipes_path, class: "btn btn-secondary" %>
</div>
<br>
<% if can? :create, @recipe %>
  <div class="d-flex justify-content-between">
    <%= link_to "Generate shopping List", general_shopping_list_index_path, class: "btn btn-primary", type: "button" %>
    <%= button_to "Add ingredient", recipe_recipe_foods_path(params[:id]), method: :get, class: "btn btn-warning", type: "button" %>
  </div>
<% end %>
<hr>
<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <% if can? :destroy, @recipe %>
        <th scope="col" class="d-flex justify-content-around">Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @recipe_foods.each do |recipe_food|%>
      <% food = @foods.find_by(id: recipe_food.food_id)%>
      <tr>
        <th scope="row"><%= food.name%></th>
        <td><%= "#{recipe_food.quantity} #{food.measurement_unit}" %></td>
        <td>US$ <%= food.price * recipe_food.quantity%></td>
        <% if can? :update, recipe_food %>
          <td class="d-flex justify-content-evenly">
            <%= button_to "Modify", recipe_recipe_foods_path(params[:id]), method: :get, class: "btn btn-primary", type: "button" %>
          <% end %>
          <% if can? :destroy, recipe_food %>
            <%= button_to "Remove", recipe_recipe_food_path(params[:id], recipe_food.id), method: :delete, class: "btn btn-danger", type: "button" %>
          </td>
        <% end %>
      </tr>
    <%end%>
  </tbody>
</table>