config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'
  resources :public_recipes, controller: 'public_recipes'
  resources :recipe_foods

  resources :foods
  resources :recipes do
      resources :recipe_foods do
        put 'increment_quantity', on: :member
        put 'decrement_quantity', on: :member
      end
      member do
    put :make_private
  end
  end
  resources :users
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.where(user: current_user)
  end

  def show; end

  def new
    @food = Food.new
  end

  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement Unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h6><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h6>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :measurement_unit, class: 'form-label' %>
    <%= form.text_field :measurement_unit, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :price, class: 'form-label' %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>
  <div>
    <%= form.label :quantity, class: 'form-label' %>
    <%= form.number_field :quantity, class: 'form-control' %>
  </div>
  <div>
    <%= form.submit class: 'btn btn-primary m-2' %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<div class="container justify-contetn-center w-50">
  <h1>Editing food</h1>
  <%= render "form", food: @food %>
  <br>
  <div>
    <%= link_to "Show this food", @food %> |
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/index.html.erb
<div class="container d-flex flex-column w-75">
  <div class="d-flex justify-content-between">
    <h1>Foods</h1>
    <div class="d-flex align-items-center">
      <%= link_to "New food +", new_food_path, class: 'btn btn-outline-primary' %>
    </div>
  </div>
  <div id="foods">
    <% if @foods.length > 0 %>
      <table class="table">
        <thead class="table-dark">
          <tr>
            <th scope="col">Food</th>
            <th scope="col">Measuremnet Unit</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td> <%= food.name%> </td>
              <td> <%= food.measurement_unit%> </td>
              <td> <%= food.price%> </td>
              <td>
                <div class="d-flex gap-2">
                  <%= link_to "Edit", edit_food_path(food), class: 'btn btn-sm btn-outline-primary' %>
                  <%= button_to "Delete", food, method: :delete, class: 'd-flex btn btn-sm btn-danger' %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>No Food Available</h3>
    <%end%>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container d-flex-justify-content-center w-50">
  <h1>New food</h1>
  <%= render "form", food: @food %>
  <br>
  <div>
    <%= link_to "Back to foods", foods_path %>
  </div>
</div>

app/views/foods/show.html.erb
<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>