config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'
  resources :public_recipes, controller: 'public_recipes'
  resources :recipe_foods

  resources :foods
  resources :recipes do
      resources :recipe_foods do
        put 'increment_quantity', on: :member
        put 'decrement_quantity', on: :member
      end
      member do
    put :make_private
  end
  end
  resources :users
  resources :general_shopping_list, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
    @foods = Food.where(user_id: current_user.id).order(:name)
    @recipe = Recipe.find(params[:recipe_id])
  end

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    respond_to do |format|
      if @recipe_food.save
        format.html do
          redirect_to recipe_recipe_foods_path(params[:recipe_id]), notice: 'Recipe food was successfully created.'
        end
        format.json { render :show, status: :created, location: @recipe_food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_food_url(@recipe_food), notice: 'Recipe food was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html do
        redirect_back(fallback_location: recipe_recipe_foods_path(params[:recipe_id]),
                      notice: 'Recipe food was successfully destroyed.')
      end
      format.json { head :no_content }
    end
  end

  def increment_quantity
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.quantity += 1
    @recipe_food.save
    redirect_back(fallback_location: recipe_recipe_foods_path(params[:recipe_id]))
  end

  def decrement_quantity
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.quantity -= 1
    @recipe_food.save
    redirect_back(fallback_location: recipe_recipe_foods_path(params[:recipe_id]))
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.permit(:quantity, :food_id, :recipe_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/index.html.erb
<% if can? :create, @recipe %>
<div class="d-flex justify-content-between">
<h1>Recipe foods</h1>
<%= link_to "Done", recipe_path(params[:recipe_id]), class: "btn btn-warning my-2" %>
</div>

<table class="table table-dark table-striped">
      <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col" class= "d-flex justify-content-around">Quantity</th>
    </tr>
      </thead>
  <tbody>

<% @foods.each do |food|%>
<% recipe_food = @recipe_foods.find_by(food_id: food.id, recipe_id: params[:recipe_id]) %>
    <tr>
      <th scope="row"><%= food.name%></th>
      <td class="d-flex justify-content-around">
      <% if recipe_food.nil? %>
      <%= button_to "Add", recipe_recipe_foods_path(recipe_id: params[:recipe_id], food_id: food.id, quantity: 1), method: :post, class:"btn btn-primary" %>
      <% else %>
      <% unless recipe_food.quantity <=0 %>
        <%= button_to " - ", decrement_quantity_recipe_recipe_food_path(recipe_food, recipe_food.id, params[:recipe_id]), method: :put, class: "mx-3" %>
      <% end %>
      <%= "#{recipe_food.quantity} #{food.measurement_unit}" %>
      <%= button_to " + ", increment_quantity_recipe_recipe_food_path(recipe_food, recipe_food.id, params[:recipe_id]), method: :put, class: "mx-3" %>
      <% end %>
      </td>
    </tr>
<%end%>
  </tbody>
  </table>
<% end %>